---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
  version: "9.4.3"
  bootstrap: true
  valuesContent: |-
    # safe ingress needs to come via GitOps .... maybe treafik
    server:
      extraArgs:
        - --insecure

    # no ha - the setup should only shoe possibility
    # I need to save memory ... ahhhh
    redis-ha:
      enabled: false
    controller:
      replicas: 1
    server:
      replicas: 1
    repoServer:
      replicas: 1
    applicationSet:
      replicas: 1
